### ISSUE TITLE
Wrong element name for response processors

### ISSUE THREAD

**Issue by jonaslepsoy** [enonic/app-vwo#358]
https://github.com/enonic/app-vwo/blob/1463bee2329a200536bcb4ac7d961af4f3654b11/src/main/resources/site/site.xml#L16-L18

`<filters>` is not the correct element name for declaring response processors, but `<processors>` is. This app never adds the VWO code snippet to the site, so tracking won't work at all!

See the [developer docs](https://developer.enonic.com/docs/xp/stable/cms/response-processors#trigger) for how response processors are declared.

**Comment by alansemenov** [comment]
@jonaslepsoy Thanks for reporting this! We have released a fix in version 1.4.2. Please install, test and let us know if everything's ok.

**Comment by jonaslepsoy** [comment]
Works like a charm! Thanks for fixing!
